# This file contains the definition of what a copyright header should contain.
# The $CURRENT_YEAR can't be added here programatically, so it should be updated manually each year.

one_date_re: "^# Copyright (?P<year>2026)"
two_date_re: "^# Copyright (?P<from>[0-9]{4})-(?P<to>2026)"
one_date_format: "^# Copyright {year}"
two_date_format: "^# Copyright {from}-{to}"
license_file: LICENSE
