ignore:
  - "docs"
  - "test"
  - "orchestrator/core/devtools"
  - "orchestrator/core/migrations"
  - "orchestrator/core/cli/generator/templates"
  - "orchestrator/core/cli/generator/custom_templates"
