{
 "title": "Workflow Orchestrator",
 "description": "An example dashboard that displays some of the available metric endpoints",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Orchestrator engine status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wfo_engine_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total workflow count",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by(is_task) (wfo_process_count)",
     "legendFormat": "Is task: {{is_task}}"
    }
   ]
  },
  {
   "title": "Subscriptions in sync",
   "type": "gauge",
   "description": "Sync status for all subscriptions that are not terminated.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(wfo_subscriptions_count{lifecycle_state!=\"terminated\", insync=\"True\"}) / sum(wfo_subscriptions_count{lifecycle_state!=\"terminated\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "targets": [
    { "expr": "wfo_active_process_count", "legendFormat": "Active processes" }
   ]
  },
  {
   "title": "Active subscriptions",
   "type": "piechart",
   "description": "Currently active subscription count per product",
   "gridPos": { "h": 14, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(product_name) (wfo_subscriptions_count{lifecycle_state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed workflows",
   "type": "timeseries",
   "description": "Processes with \"failed\" as last state, grouped by workflow name.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(workflow_name) (wfo_process_count{last_status=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}