"""Adding an importance value for steps.

Revision ID: bfa6c728afd9
Revises: 544fd845554d
Create Date: 2026-09-30 21:57:01.372468

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bfa6c728afd9'
down_revision = '544fd845554d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_steps', sa.Column('importance', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_steps', 'importance')
    # ### end Alembic commands ###
