name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["triage", "feature"]
projects: ["workfloworchestrator/orchestrator-core", "workfloworchestrator/orchestrator-ui", "workfloworchestrator/oauth2-lib", "workfloworchestrator/nwa-stdlib"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: What should we build?
      description: What feature are we missing? What would an ideal solution look like?
      placeholder: Tell us what we should build!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant pseudo code
      description: Please write, copy or paste any relevant log output and or code. This will be automatically formatted into code, so no need for backticks.
      render: shell