# Copyright 2019-2025 SURF, GÉANT.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from sqlalchemy_utils.types.ltree import Ltree

from orchestrator.db import SubscriptionTable
from orchestrator.db.models import AiSearchIndex
from orchestrator.llm_settings import llm_settings
from orchestrator.search.core.types import EntityType, FieldType

GROUND_TRUTH_FILE = Path(__file__).parent / "data" / "ground_truth.json"
MODELS_FILE = GROUND_TRUTH_FILE.parent / "models.json"


@dataclass
class BenchmarkQuery:
    """A benchmark query with expected result ordering."""

    query_text: str
    description: str
    expected_ranking: list[str] | None = None


@dataclass
class ModelConfig:
    """Configuration for an embedding model to benchmark.

    Note: API keys and base URLs come from llm_settings (OPENAI_API_KEY, OPENAI_BASE_URL).
    This config only specifies the model name, LiteLLM model string, and expected dimension.
    """

    name: str  # Display name (e.g., "OpenAI Large")
    model: str  # LiteLLM model string (e.g., "openai/text-embedding-3-large")
    dimension: int  # Expected dimension (for truncation warnings)


def load_ground_truth() -> dict:
    """Load ground truth data from JSON file.

    Returns:
        Dictionary containing:
        - metadata: Info about baseline model, dimension, generation timestamp
        - entities: List of entities with embeddings
        - queries: List of queries with embeddings and expected rankings
    """
    if not GROUND_TRUTH_FILE.exists():
        return {"metadata": {}, "entities": [], "queries": []}

    with open(GROUND_TRUTH_FILE) as f:
        return json.load(f)


def load_benchmark_queries() -> list[BenchmarkQuery]:
    """Load benchmark queries from ground truth.

    Returns:
        List of BenchmarkQuery objects with query text, description, and expected rankings.
    """
    ground_truth = load_ground_truth()
    return [
        BenchmarkQuery(
            query_text=str(q["query_text"]),
            description=str(q.get("description", "")),
            expected_ranking=q.get("expected_ranking"),
        )
        for q in ground_truth.get("queries", [])
    ]


def load_model_configs() -> list[ModelConfig]:
    """Load model configurations from models.json.

    Edit test/integration_test/search/data/models.json to benchmark different models.
    """

    with open(MODELS_FILE) as f:
        data = json.load(f)
        return [
            ModelConfig(
                name=m["name"],
                model=m["model"],
                dimension=m["dimension"],
            )
            for m in data.get("models", [])
        ]


def get_expected_ranking(query_text: str) -> list[str]:
    """Get expected ranking for a query from ground truth data.

    Args:
        query_text: The query text to look up

    Returns:
        List of entity IDs in expected ranking order

    Raises:
        KeyError: If query_text is not found in ground truth data
    """
    ground_truth = load_ground_truth()
    queries_by_text = {q["query_text"]: q for q in ground_truth.get("queries", [])}
    return queries_by_text[query_text]["expected_ranking"]


def save_ground_truth(entities: list[dict], queries: list[dict]) -> None:
    """Save ground truth data to JSON file.

    Args:
        entities: List of entity records with embeddings
        queries: List of query records with embeddings and expected rankings
    """
    ground_truth = {
        "metadata": {
            "baseline_model": llm_settings.EMBEDDING_MODEL,
            "dimension": llm_settings.EMBEDDING_DIMENSION,
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "description": "Ground truth embeddings and rankings for search integration tests and benchmarking. Generated by running queries through the search engine with the baseline model.",
        },
        "entities": entities,
        "queries": queries,
    }

    with open(GROUND_TRUTH_FILE, "w") as f:
        json.dump(ground_truth, f, indent=2)


def index_subscription(
    subscription: SubscriptionTable, embedding: list[float], session, subscription_index: int = 1
) -> None:
    """Index a single subscription into AiSearchIndex with multiple records.

    Creates:
    - description field with embedding (for semantic search)
    - status field without embedding (for filtering)
    - insync field without embedding (for filtering)
    - start_date field without embedding (for temporal grouping)

    Args:
        subscription: The subscription to index
        embedding: The embedding vector for the subscription description
        session: The SQLAlchemy session to use
        subscription_index: Index of subscription (1-based) used to generate test dates
    """
    # Index description with embedding
    index_record = AiSearchIndex(
        entity_type=EntityType.SUBSCRIPTION.value,
        entity_id=subscription.subscription_id,
        entity_title=subscription.description[:50],
        path=Ltree("description"),
        value=subscription.description,
        value_type=FieldType.STRING.value,
        content_hash=f"test_hash_{subscription.subscription_id}",
        embedding=embedding,
    )
    session.add(index_record)

    # Add status field (no embedding)
    status_record = AiSearchIndex(
        entity_type=EntityType.SUBSCRIPTION.value,
        entity_id=subscription.subscription_id,
        entity_title=subscription.description[:50],
        path=Ltree("status"),
        value=subscription.status.value if hasattr(subscription.status, "value") else str(subscription.status),
        value_type=FieldType.STRING.value,
        content_hash=f"test_hash_status_{subscription.subscription_id}",
        embedding=None,
    )
    session.add(status_record)

    # Add insync field (no embedding)
    insync_record = AiSearchIndex(
        entity_type=EntityType.SUBSCRIPTION.value,
        entity_id=subscription.subscription_id,
        entity_title=subscription.description[:50],
        path=Ltree("insync"),
        value=str(subscription.insync).lower(),
        value_type=FieldType.BOOLEAN.value,
        content_hash=f"test_hash_insync_{subscription.subscription_id}",
        embedding=None,
    )
    session.add(insync_record)

    # Cycle through all 12 months: index 1-12 -> Jan-Dec, 13-22 -> Jan-Oct
    month = ((subscription_index - 1) % 12) + 1
    start_date = f"2024-{month:02d}-01T00:00:00"

    start_date_record = AiSearchIndex(
        entity_type=EntityType.SUBSCRIPTION.value,
        entity_id=subscription.subscription_id,
        entity_title=subscription.description[:50],
        path=Ltree("subscription.start_date"),
        value=start_date,
        value_type=FieldType.DATETIME.value,
        content_hash=f"test_hash_start_date_{subscription.subscription_id}",
        embedding=None,
    )
    session.add(start_date_record)
