CITY_TYPE = "city_type"
DOMAIN = "domain"
PORT_SPEED = "port_speed"
SERVICE_SPEED = "service_speed"
IMS_CIRCUIT_ID = "ims_circuit_id"
IPAM_PREFIX_ID = "ipam_prefix_id"
PEER_GROUP_SUBSCRIPTION_ID = "peer_group_subscription_id"
GRAPHQL_ENDPOINT = "/api/graphql"
GRAPHQL_HEADERS = {"Content-Type": "application/json"}
