# Copyright 2019-2026 SURF, GÉANT.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import CoreSchema


def _rewrite_datetime_to_unix_timestamp(schema: Any) -> None:
    """Rewrite datetime declarations from {string, date-time} to {number, unix-timestamp}."""
    if isinstance(schema, dict):
        if schema.get("type") == "string" and schema.get("format") == "date-time":
            schema["type"] = "number"
            schema["format"] = "unix-timestamp"
            return
        for value in schema.values():
            _rewrite_datetime_to_unix_timestamp(value)
    elif isinstance(schema, list):
        for item in schema:
            _rewrite_datetime_to_unix_timestamp(item)


class OrchestratorBaseModel(BaseModel):
    # Unable to refactor in a neat way without using an ugly recursive function. Leaving Pydantic v1 functionality intact
    # Edit: The recursive function is implemented above because autogenerated clients need the openapi.json to be truthfull.
    model_config = ConfigDict(
        json_encoders={
            datetime: lambda dt: dt.timestamp(),
        }
    )

    @classmethod
    def __get_pydantic_json_schema__(cls, schema: CoreSchema, handler: GetJsonSchemaHandler) -> JsonSchemaValue:
        # Pydantic's default schema for ``datetime`` is ``{type: string, format: date-time}``,
        # but ``json_encoders`` above serializes it as a Unix epoch float at the wire.
        # Rewrite the declared schema to match the wire format so OpenAPI consumers
        # (and fastmcp's response validation) see the truth.
        json_schema = handler(schema)
        _rewrite_datetime_to_unix_timestamp(json_schema)
        return json_schema
