"""Make workflow description mandatory.

Revision ID: 68d14db1b8da
Revises: bac6be6f2b4f
Create Date: 2025-02-20 16:39:34.889953

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68d14db1b8da"
down_revision = "bac6be6f2b4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # backfill description with emoty string, just to be sure
    conn = op.get_bind()
    backfill_wf_description_with_empty_string(conn)
    op.alter_column("workflows", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workflows", "description", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def backfill_wf_description_with_empty_string(conn: sa.engine.Connection) -> None:
    conn.execute(
        sa.text(
            """
            UPDATE workflows SET description ='' WHERE description is NULL
            """
        ),
    )
