"""Make workflow description mandatory.

Revision ID: 68d14db1b8da
Revises: bac6be6f2b4f
Create Date: 2025-02-20 16:39:34.889953

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68d14db1b8da"
down_revision = "bac6be6f2b4f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_input_state_input_state_id", table_name="input_states")
    op.create_index(op.f("ix_input_states_input_state_id"), "input_states", ["input_state_id"], unique=False)
    op.alter_column("workflows", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workflows", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_index(op.f("ix_input_states_input_state_id"), table_name="input_states")
    op.create_index("ix_input_state_input_state_id", "input_states", ["input_state_id"], unique=False)
    # ### end Alembic commands ###
