"""Add User Input table.

Revision ID: 0373ed2d074f
Revises: 4fjdn13f83ga
Create Date: 2025-02-11 10:37:06.261882

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql
from orchestrator import db

# revision identifiers, used by Alembic.
revision = '0373ed2d074f'
down_revision = '4fjdn13f83ga'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('user_input_id', sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('pid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('user_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_time', db.models.UtcTimestamp(timezone=True), server_default=sa.text('current_timestamp'), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['processes.pid'], ),
    sa.PrimaryKeyConstraint('user_input_id')
    )
    op.create_index(op.f('ix_user_input_user_input_id'), 'user_input', ['user_input_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_input_user_input_id'), table_name='user_input')
    op.drop_table('user_input')
    # ### end Alembic commands ###
