name: Check alembic migrations

on:
  pull_request:
    paths:
      - 'orchestrator/core/migrations/**'

env:
  UV_LOCKED: true  # Assert that the `uv.lock` will remain unchanged

jobs:
  build:
    name: Check alembic migrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          # It is considered best practice to pin to a specific uv version.
          version: "0.12.3"

      - name: Ensure there is 1 migration head
        run: |
          NUM_HEADS=$(uv run alembic -c orchestrator/core/migrations/alembic.ini history | grep -cF '(head)')
          echo "Found '$NUM_HEADS' alembic heads"
          if [ "$NUM_HEADS" != "1" ]; then
            echo "There should be exactly 1 alembic head and no branchpoints"
            exit 1
          fi
