name: Upload Python Package

on:
  release:
    types: [created]

env:
  UV_LOCKED: true  # Assert that the `uv.lock` will remain unchanged

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v8.1.0
      with:
        # It is considered best practice to pin to a specific uv version.
        version: "0.11.7"
        python-version: "3.x"

    - name: Build package
      run: uv build

    - name: Upload dist artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish:
    needs: build
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
