name: Scheduled build and test

on:
  workflow_dispatch:  # Manual run
  schedule:  # Targets the default branch
    - cron: '0 7 * * MON'  # TODO github's cron pattern doesn't support modulo, so it runs every week. Add a job that silently stops the workflow every uneven week
  push:
    branches:
      - "1256-schedule-build-and-notify" # TODO remove

env:
  CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}


jobs:
  run_build:
    uses: ./.github/workflows/run-linting-tests.yml

  run_tests:
    uses: ./.github/workflows/run-unit-tests.yml
    needs: [run_build]

  notify_build_failed:
    needs: [run_build]
    if: ${{ failure() }}
    uses: ./.github/workflows/slack-notify.yml
    with:
      message: "Build failed "
      success: false
      channel: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
    secrets:
      CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}

  notify_test_failed:
    needs: [run_tests]
    if: ${{ failure() }}
    uses: ./.github/workflows/slack-notify.yml
    with:
      message: "Successful build but failed test"
      success: false
      channel: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
    secrets:
      CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}

  notify_test_success:
    needs: [run_tests]
    if: ${{ success() }}
    uses: ./.github/workflows/slack-notify.yml
    with:
      message: "Successful build but failed test"
      success: true
      channel: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
    secrets:
      CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}
