name: Scheduled build and test

on:
  schedule:  # Targets the default branch
    - cron: '0 6 * * MON'  # TODO github's cron pattern doesn't support modulo, so it runs every week. Add a job that silently stops the workflow every uneven week
  push:
    branches:
      - "1256-schedule-build-and-notify" # TODO remove

jobs:
  # check_week:
  #   steps:
  #     - run:

  run_build:
    uses: ./.github/workflows/run-linting-tests.yml
    needs: [check_week]

  run_tests:
    uses: ./.github/workflows/run-unit-tests.yml
    needs: [run_build]


  slack:
      needs: [run_tests] # set needs only last job except this job
      runs-on: ubuntu-latest
      if: always() # set always
      steps:
          # run this action to get workflow conclusion
          # You can get conclusion via env (env.WORKFLOW_CONCLUSION)
        - uses: technote-space/workflow-conclusion-action@v2
        - run: echo "ICON=$([ \"$WORKFLOW_CONCLUSION\" == \"success\" ] && echo white_check_mark || echo zap)" >> $GITHUB_ENV
        - uses: 8398a7/action-slack@v3
          with:
            status: ${{ env.WORKFLOW_CONCLUSION }} # neutral, success, skipped, cancelled, timed_out, action_required, failure
            # status: failure
            channel: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
            icon_emoji: ${{ env.ICON }}
          env:
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}
          if: ${{ contains(fromJson('["failure", "success"]'), env.WORKFLOW_CONCLUSION) }}  # notify on success or failure

  # notify_build_failed:
  #   needs: [run_build]
  #   if: ${{ failure() }}
  #   uses: ./.github/workflows/slack-notify.yml
  #   with:
  #     message: "Build failed for"
  #     success: false
  #   secrets:
  #     CHANNEL: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
  #     CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}

  # notify_test_failed:
  #   needs: [run_tests]
  #   if: ${{ failure() }}
  #   uses: ./.github/workflows/slack-notify.yml
  #   with:
  #     message: "Successful build but failed test"
  #     success: false
  #   secrets:
  #     CHANNEL: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
  #     CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}

  # notify_test_success:
  #   needs: [run_tests]
  #   if: ${{ success() }}
  #   uses: ./.github/workflows/slack-notify.yml
  #   with:
  #     message: "Successfully built and tested"
  #     success: true
  #   secrets:
  #     CHANNEL: ${{ secrets.CI_SLACK_NOTIFICATION_CHANNEL }}
  #     CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}
