name: Send Slack Notification

on:
  workflow_call:
    inputs:
      message:
        description: 'The message to post'
        type: string
        required: true
      success:
        description: 'Indicates success of the calling workflow'
        type: boolean
        required: true
      username:
        description: 'Slack notification is posted as this user'
        type: string
        default: 'Github Pipeline'
        required: false
    secrets:
      CHANNEL:
        description: 'Channel to post in'
        required: true
      CI_SLACK_WEBHOOK_URL:
        description: 'Valid Slack webhook URL'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f2-)" >> $GITHUB_ENV
      - run: wget --quiet https://raw.githubusercontent.com/workfloworchestrator/nitpick-style/main/ci/scripts/slack.sh
      - run: chmod +x slack.sh
      - run: ./slack.sh "${{ secrets.CHANNEL }}" "${{ inputs.message }} $REPOSITORY_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" zap "${{ inputs.username }}"
        if: ${{ inputs.success == false }}
      - run: ./slack.sh "${{ secrets.CHANNEL }}" "${{ inputs.message }} $REPOSITORY_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" white_check_mark "${{ inputs.username }}"
        if: ${{ inputs.success == true }}
    env:
      CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}
