name: Send Slack Notification

on:
  workflow_call:
    inputs:
      username:
        description: 'Slack notification is posted as this user'
        type: string
        default: 'Github Pipeline'
        required: false
      message:
        required: true
        type: string
      success:
        required: true
        type: boolean
    secrets:
      CI_SLACK_WEBHOOK_URL:
        required: true
      CHANNEL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f2-)
      - run: wget --quiet https://raw.githubusercontent.com/workfloworchestrator/nitpick-style/main/ci/scripts/slack.sh
      - run: chmod +x slack.sh
      - run: ./slack.sh "${{ secrets.CHANNEL }}" "${{ inputs.message }} for $REPOSITORY_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" zap "${{ inputs.username }}"
        if: ${{ inputs.success == true }}
      - run: ./slack.sh "${{ secrets.CHANNEL }}" "${{ inputs.message }} for $REPOSITORY_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" white_check_mark "${{ inputs.username }}"
        if: ${{ inputs.success == false }}
    env:
      CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}
