name: Generate uv.lock report

on:
  pull_request:
    paths:
      - 'uv.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: mw-root/uv-lock-report@dc61e2c8bceda25c9008d60b8bcda2dea8ab5aef # v0.14.1
        with:
          output-format: "table"
          github-token: ${{ secrets.GITHUB_TOKEN }}
